services:
  - name: client
    type: web
    staticSite: true
    rootDir: client
    buildCommand: npm install && npm run build
    publishDir: dist
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_BACKEND_URL
        value: https://quickchat-app-api.onrender.com

  - name: server
    type: web
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
